name: ivy_path
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.66.2
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.1
  json_annotation: ^4.8.1
  flutter_staggered_grid_view: ^0.7.0
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  flutter_html: ^3.0.0-beta.2
  flutter_math_fork: ^0.7.3
  flutter_html_math: ^3.0.0-alpha.4
  flutter_markdown: ^0.7.7+1
  encrypt: ^5.0.3
  path_provider: ^2.1.5
  firebase_core: ^2.27.1
  firebase_database: ^10.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/