// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjU8rN8iCohn3Mp6aoWSUznN4geLNq7PA',
    appId: '1:871115568480:web:be505eb99fd15d32601a05',
    messagingSenderId: '871115568480',
    projectId: 'ivypath',
    authDomain: 'ivypath.firebaseapp.com',
    databaseURL: 'https://ivypath-default-rtdb.firebaseio.com',
    storageBucket: 'ivypath.firebasestorage.app',
    measurementId: 'G-1JRJCWZXM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VSfcFjIIITZiM5GUbU0HAXt5KTnCciI',
    appId: '1:871115568480:android:c273998bd16af0b6601a05',
    messagingSenderId: '871115568480',
    projectId: 'ivypath',
    databaseURL: 'https://ivypath-default-rtdb.firebaseio.com',
    storageBucket: 'ivypath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8mhAYCWVND79LHkDXFLmhwvtUS93Q-ag',
    appId: '1:871115568480:ios:d52622d8705a5811601a05',
    messagingSenderId: '871115568480',
    projectId: 'ivypath',
    databaseURL: 'https://ivypath-default-rtdb.firebaseio.com',
    storageBucket: 'ivypath.firebasestorage.app',
    iosBundleId: 'com.example.ivyPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8mhAYCWVND79LHkDXFLmhwvtUS93Q-ag',
    appId: '1:871115568480:ios:d52622d8705a5811601a05',
    messagingSenderId: '871115568480',
    projectId: 'ivypath',
    databaseURL: 'https://ivypath-default-rtdb.firebaseio.com',
    storageBucket: 'ivypath.firebasestorage.app',
    iosBundleId: 'com.example.ivyPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjU8rN8iCohn3Mp6aoWSUznN4geLNq7PA',
    appId: '1:871115568480:web:a7f45702e72f3b12601a05',
    messagingSenderId: '871115568480',
    projectId: 'ivypath',
    authDomain: 'ivypath.firebaseapp.com',
    databaseURL: 'https://ivypath-default-rtdb.firebaseio.com',
    storageBucket: 'ivypath.firebasestorage.app',
    measurementId: 'G-Y96K1PDZMH',
  );
}
